name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-flags: --debug

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Clone maim_message
      run: git clone --depth 1 https://github.com/MaiM-with-u/maim_message maim_message

    - name: Generate image tags
      id: tags
      run: |
        current_date=$(date -u +'%Y-%m-%d')
        echo "latest_tag=$DOCKERHUB_USER/maimbot-adapter:latest" >> $GITHUB_OUTPUT
        echo "date_tag=$DOCKERHUB_USER/maimbot-adapter:$current_date" >> $GITHUB_OUTPUT
        echo "full_tags=$DOCKERHUB_USER/maimbot-adapter:latest,$DOCKERHUB_USER/maimbot-adapter:$current_date" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.tags.outputs.full_tags }}
        push: true
        cache-from: type=registry,ref=$DOCKERHUB_USER/maimbot-adapter:buildcache
        cache-to: type=registry,ref=$DOCKERHUB_USER/maimbot-adapter:buildcache,mode=max
        labels: |
          org.opencontainers.image.created=${{ steps.tags.outputs.date_tag }}
          org.opencontainers.image.revision=${{ github.sha }}